### PR TITLE
Add instructions on how to unzip the dataset

### PR DESCRIPTION
**Pull request by epeters3**
I noticed a couple people have gotten confused on how to consume the dataset files from Google Drive. This PR adds instructions  for that.

### CODE REVIEW

**Comment by epeters3** [comment]
CC @nkicsl @guomugong (PS: thank you for open-sourcing this dataset :pray:)

**Review by guomugong — APPROVED** [review]

**Review by guomugong — APPROVED** [review]

**Review by guomugong — APPROVED** [review]
Approve

**Comment by epeters3** [comment]
Thanks so much @guomugong for your approval. It looks like you'll need to be the one to merge the PR, since I don't have write access to the repository.

**Comment by YukinoshitaLove** [comment]
@epeters3 Thank you for your contribution.

**Pull request merged**
